// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCECC0QtckzdzmY3uZmxIcwvm2XVjt1aq0',
    appId: '1:836656395960:web:142713e1739cb7b91ae64d',
    messagingSenderId: '836656395960',
    projectId: 'turnosya-test',
    authDomain: 'turnosya-test.firebaseapp.com',
    storageBucket: 'turnosya-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiAiUR9DGHbHTFY7ukQjmb61wVvsmYz3Q',
    appId: '1:836656395960:android:5e29c71c30bbf4f81ae64d',
    messagingSenderId: '836656395960',
    projectId: 'turnosya-test',
    storageBucket: 'turnosya-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_bbCuvvuW5FWEeLHnBqMK4tIsTwNAcsg',
    appId: '1:836656395960:ios:a46cdaf854778ed01ae64d',
    messagingSenderId: '836656395960',
    projectId: 'turnosya-test',
    storageBucket: 'turnosya-test.firebasestorage.app',
    iosBundleId: 'com.example.proyectoPrueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_bbCuvvuW5FWEeLHnBqMK4tIsTwNAcsg',
    appId: '1:836656395960:ios:a46cdaf854778ed01ae64d',
    messagingSenderId: '836656395960',
    projectId: 'turnosya-test',
    storageBucket: 'turnosya-test.firebasestorage.app',
    iosBundleId: 'com.example.proyectoPrueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCECC0QtckzdzmY3uZmxIcwvm2XVjt1aq0',
    appId: '1:836656395960:web:48402e00844cefe11ae64d',
    messagingSenderId: '836656395960',
    projectId: 'turnosya-test',
    authDomain: 'turnosya-test.firebaseapp.com',
    storageBucket: 'turnosya-test.firebasestorage.app',
  );
}
